### ISSUE TITLE
IAE: Resource ID must not be zero

### ISSUE THREAD

**Issue by tbremer19** [f2prateek/device-frame-generator#103]
Hello, I tried to add my own devices. I have 7 png's of each and did anything like in your description.
For now I added two devices, Nexus 4 and Nexus 5, but when I start the app I get `IllegalArgumentException: Resource ID must not be zero.`
Why? I have all png's and I also modified the DeviceModule.java...

https://gist.github.com/tbremer19/a184eb0890344289103f

Thanks for your help!

**Comment by f2prateek** [comment]
What were the png files named?

It would be easier to send me a pull request I can check out locally and test.

**Comment by tbremer19** [comment]
@f2prateek I have the same error after renaming `nexus_4_port_thumb` to `nexus_4_thumb`. Still IAE...

**Comment by f2prateek** [comment]
Upload the changes in the PR
