### ISSUE TITLE
Not able to build 

### ISSUE THREAD

**Issue by saikrishna321** [f2prateek/device-frame-generator#121]
@f2prateek i was getting the below error when  building the project 

A problem occurred configuring root project 'device-frame-generator'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not resolve com.android.support:support-annotations:23.0.0.
     Required by:
         :device-frame-generator:unspecified > com.android.support:support-v4:22.2.1
      > Could not resolve com.android.support:support-annotations:23.0.0.
         > Could not get resource 'https://maven.fabric.io/repo/com/android/support/support-annotations/23.0.0/support-annotations-23.0.0.pom'.
            > Could not GET 'https://maven.fabric.io/repo/com/android/support/support-annotations/23.0.0/support-annotations-23.0.0.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.android.support:support-annotations:23.0.0.
     Required by:
         :device-frame-generator:unspecified > com.f2prateek.rx.preferences:rx-preferences:1.0.1
      > Could not resolve com.android.support:support-annotations:23.0.0.
         > Could not get resource 'https://maven.fabric.io/repo/com/android/support/support-annotations/23.0.0/support-annotations-23.0.0.pom'.
            > Could not GET 'https://maven.fabric.io/repo/com/android/support/support-annotations/23.0.0/support-annotations-23.0.0.pom'. Received status code 401 from server: Unauthorized

**Comment by f2prateek** [comment]
You'll need an account with Fabric

**Comment by saikrishna321** [comment]
@f2prateek  i have created an account, but i was unable to access the dependency repo URL
 when i hit the below URL 

https://maven.fabric.io/repo/com/android/support/support-annotations/23.0.0/support-annotations-23.0.0.pom

i'm redirected to 

https://twittersdk.artifactoryonline.com/twittersdk/repo/com/android/support/support-annotations/23.0.0/support-annotations-23.0.0.pom

and asked for credentials, the registered credentials does not work
