### ISSUE TITLE
Add support for Android Wear

### ISSUE THREAD

**Issue by ingbrzy** [f2prateek/device-frame-generator#123]
Is possible to add support for Android Wear?

Screenshots from wear are squared so DFG has to cut off circle with defined diameter of the watch face..

![screen](https://cloud.githubusercontent.com/assets/1762519/22163551/98b9ac90-df53-11e6-8e7d-67ec626b8b7a.png)

possible frames for ZenWatch 3

![watchface_ui_watch_black](https://cloud.githubusercontent.com/assets/1762519/22163569/a90478c8-df53-11e6-854b-3d56215552ff.png)

![watchface_ui_watch_rosegold](https://cloud.githubusercontent.com/assets/1762519/22163586/af01960c-df53-11e6-8b38-d16d4783e3ef.png)

![watchface_ui_watch_white](https://cloud.githubusercontent.com/assets/1762519/22164915/9b5f274e-df59-11e6-99e1-d18fe2da531c.png)

**Comment by f2prateek** [comment]
It should be possible. The current code uses the top left corners to align the frame and images, but could refactor it to align it based on the center instead.

**Comment by ingbrzy** [comment]
OK great..!
If you add support for Wear , I can push frames for it.. (Circle style)

Thanks

**Comment by f2prateek** [comment]
Sorry I probably won't have time to get to it. Open to PRs though!

**Comment by ingbrzy** [comment]
What if we will do it much simpler only for Wear? Frame will be top layer which will have white background except circle screen which will be transparent... and screenshot goes as bottom layer so it doesn't need to be cut into the circle by app.. also screenshot positioning doesn't need to be from center as it has still black corners...

like here is
![img_moto_360_2015](https://cloud.githubusercontent.com/assets/1762519/22180439/a3eada8a-e070-11e6-99cf-a526c1b5f647.png)

so for now will be enough just add layers order for wear support...
